spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:postgresql://localhost:5432/db_wallet
    username: postgres
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 9002

internal:
  api-key: secret123