spring:
  application:
    name: wallet-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_wallet}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8082

internal:
  api-key: ${INTERNAL_API_KEY}